[package]
org = "ballerinax"
name = "jaeger_server_tests"
version = "0.1.0"
distribution = "2201.8.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="jaeger"
repository="local"
version = "@toml.version@"
